# # # # # a="Harry"
# # # # # print(a[:4])
# # # # # print(a[2:])
# # # # # print(a[-3])
# # # # # print(a[-4])
# # # # # print(a[4])
# # # # # print(a[-4:-1])
# # # # # print(a[-1:])
# # # # # d=a[0:4:3]
# # # # name="HarryIsGood"
# # # # d=name[0::3]
# # # # print(d)
# # # story="once upon a time there is a youtuber name Harry uploaded who uploded python course"
# # # # String functions
# # # print(len(story))
# # # print(story.endswith("se"))
# # # print(story.count("a"))
# # # print(story.count("A"))
# # # print(story.find("Harry"))
# # # print(story.replace("Harry","code"))
# # # a = "he is very good\n and \tbest \
# # #     \
# # #     \
# # #     \
# # #     \
# # #     \
# # #     \
# # #     \
# # #     \
# # #     or teching  coding"
# # # print(a)

# # # name=input()
# # # 
# # a=input()                #name
# # b=input()                #date
# # print("'''Dear ",a)
# # print("You are selected!")
# # print("You are selected!")
# # print("You are selected!")
# # print(b,"'''")




# a=[3,4,54,62,4,3]
# print(a)
# print(a[0])
# print(a[1])
# print(a[2])
# print(a[3])
# print(a[4])
# print(a[5])
# print(a[-2])
# print(a[-5])
# a[-3]=999
# print(a)
# print(a[-3])

print
